version: "3"
services:
    mongo:
        container_name: mongo
        image: mongo:4.4
        volumes:
            - ./data:/data/db
        ports:
            - "27010:27017"
        networks:
            - express
    register-app:
        container_name: express-app
        image: expressapi
        build: .
        ports:
            - 4005:8000
        networks:
            - express
        depends_on:
            - mongo

networks:
    express:
        driver: bridge
